### ISSUE TITLE
FIXED - sms_auth.py not sending a code

### ISSUE THREAD

**Issue by gstangel** [MMcintire96/python_TinderAPI#6]
I can't get the script to send a verification code.  Is this unique for me, or is anyone else experiencing this?

**Comment by autisticvegan** [comment]
also having this problem
edit: workaround I did: just do it in the web interface then get your token from the local storage. Need someone teach me hacking plss im a noob :)

**Comment by MMcintire96** [comment]
Just pushed a fix for this, fixed another auth issue and added a photo for how to get the token through chrome inspector.

You can get put on an sms_wait_list of some sort so just a heads up. This happens in the browser if you request the code multiple times without fully authenticating.

**Comment by MMcintire96** [comment]
Actually will leave this open until I hear back from @internals-gs or @autisticvegan as I am not sure what other endpoints changed

**Comment by connor-create** [comment]
I just went through and checked all of the get requests for the user data as I was working with it when you updated it.  They all seemed to work fine.  Did not get around to the update functions but will probably take a look at them all tomorrow.  I still was not able to get the sms auth to work via the script and had to go to the site to pull the token myself, but that may (most likely) have been because of myself.   I will try it again tomorrow.

**Comment by MMcintire96** [comment]
@connor-create It appears that sms is not sending from the **browser** or the script. The authentication method returns 200 (success) but the data shows {"sms_sent" : False}. I actually think this is an issue with Tinder's sms microservice currently. I will keep checking it throughout the week.

Good to hear that the endpoints are working. Thanks for checking.

**Comment by connor-create** [comment]
I believe the other tinder api gits were having issue with the same thing anyways, definitely on Tinder's end. Thanks for the fix and info.
